export enum TipoHistorialPerfilProfesor {
  CARRERAS = 'CARRERAS',
  CURSO = 'CURSO',
  PERFIL_ACADEMICO = 'PERFIL_ACADEMICO',
}

export enum AccionHistorialPerfilProfesor {
  ACTUALIZAR_CARRERAS = 'ACTUALIZAR_CARRERAS',
  SOLICITAR_CURSO = 'SOLICITAR_CURSO',
  APROBAR_CURSO = 'APROBAR_CURSO',
  RECHAZAR_CURSO = 'RECHAZAR_CURSO',
  INACTIVAR_CURSO = 'INACTIVAR_CURSO',
  SOLICITAR_PERFIL = 'SOLICITAR_PERFIL',
  APROBAR_PERFIL = 'APROBAR_PERFIL',
  RECHAZAR_PERFIL = 'RECHAZAR_PERFIL',
  INACTIVAR_PERFIL = 'INACTIVAR_PERFIL',
}
