export enum TipoAtestadoProfesor {
  TITULO_ACADEMICO = 'TITULO_ACADEMICO',
  CERTIFICACION = 'CERTIFICACION',

  EXPERIENCIA_DOCENTE = 'EXPERIENCIA_DOCENTE',
  EXPERIENCIA_PROFESIONAL = 'EXPERIENCIA_PROFESIONAL',
  CAPACITACION = 'CAPACITACION',

  OTRO = 'OTRO',
}

export const TIPOS_ATESTADO_PROFESOR = Object.values(TipoAtestadoProfesor);
