export enum RolSistema {
  ADMIN_GLOBAL = 'ADMIN_GLOBAL',
  COORDINADOR = 'COORDINADOR',
  PROFESOR = 'PROFESOR',
  ASISTENTE_ESTUDIANTIL = 'ASISTENTE_ESTUDIANTIL',
}

export const ROLES_SISTEMA = Object.values(RolSistema);
