export enum TipoMobiliarioAula {
  PUPITRE = 'PUPITRE',
  MESA_INDIVIDUAL = 'MESA_INDIVIDUAL',
  MESA_GRUPAL = 'MESA_GRUPAL',
  MESA_COMPUTADORA = 'MESA_COMPUTADORA',
  BUTACA = 'BUTACA',
  SIN_MOBILIARIO = 'SIN_MOBILIARIO',
  SIN_ESPECIFICAR = 'SIN_ESPECIFICAR',
}

export const TIPOS_MOBILIARIO_AULA = Object.values(TipoMobiliarioAula);
