export enum PermisoSistema {
  PROFESORES_VER = 'PROFESORES_VER',
  ATESTADOS_VALIDAR = 'ATESTADOS_VALIDAR',
  PERFILES_DOCENTES_VALIDAR = 'PERFILES_DOCENTES_VALIDAR',
  PERFILES_ACADEMICOS_GESTIONAR = 'PERFILES_ACADEMICOS_GESTIONAR',
  PROYECCION_VER = 'PROYECCION_VER',
  PROYECCION_GESTIONAR = 'PROYECCION_GESTIONAR',
  OFERTA_VER = 'OFERTA_VER',
  OFERTA_GESTIONAR = 'OFERTA_GESTIONAR',
  PROFESORES_ASIGNAR = 'PROFESORES_ASIGNAR',
  AULAS_ASIGNAR = 'AULAS_ASIGNAR',
  AULAS_CAMBIO_AUTORIZAR = 'AULAS_CAMBIO_AUTORIZAR',
}

export const PERMISOS_SISTEMA = Object.values(PermisoSistema);
