export enum TipoRequisitoPerfil {
  FORMACION_ACADEMICA = 'FORMACION_ACADEMICA',
  IDIOMA_INSTRUMENTAL = 'IDIOMA_INSTRUMENTAL',
  EXPERIENCIA_DOCENTE = 'EXPERIENCIA_DOCENTE',
  GRADO_COMPLEMENTARIO = 'GRADO_COMPLEMENTARIO',
  IDIOMA_GLOBAL = 'IDIOMA_GLOBAL',
  EXPERIENCIA_PROFESIONAL = 'EXPERIENCIA_PROFESIONAL',
  CAPACITACIONES = 'CAPACITACIONES',
  OTROS = 'OTROS',
  JORNADA = 'JORNADA',
  HORARIO = 'HORARIO',
  CAMPUS = 'CAMPUS',
}
