export enum TipoAsignacionAcademica {
  COORDINADOR_CARRERA = 'COORDINADOR_CARRERA',
  COORDINADOR_AREA = 'COORDINADOR_AREA',
  DIRECCION_ACADEMICA = 'DIRECCION_ACADEMICA',
  ASISTENTE_CARRERA = 'ASISTENTE_CARRERA',
  ASISTENTE_AREA = 'ASISTENTE_AREA',
  ASISTENTE_DIRECCION = 'ASISTENTE_DIRECCION',
}

export const TIPOS_ASIGNACION_ACADEMICA = Object.values(
  TipoAsignacionAcademica,
);
